### PR TITLE
Restrict when `try_reserve_2` is enabled

### PR DESCRIPTION
**Pull request by smoelius**
Ref: https://github.com/camino-rs/camino/pull/21#issuecomment-1212597255

If you decide this PR is too invasive, I won't be insulted if you close it without merging.

### CODE REVIEW

**Comment by sunshowers** [comment]
Thanks. This looks fine except it pulls in a couple extra dependencies. Can those dependencies be inlined?

**Comment by sunshowers** [comment]
(My concern is that those dependencies may have their own optional features—currently, camino is a zero-dep library.)

**Comment by sunshowers** [comment]
Apologies, one more change: could this just do "stable/beta 1.64 or later, nightly 1.65 or later"? That means we can avoid the date-parsing code.

**Comment by smoelius** [comment]
> Apologies, one more change: could this just do "stable/beta 1.64 or later, nightly 1.65 or later"? That means we can avoid the date-parsing code.

What do you think the CI toolchains should be in this case?

**Comment by sunshowers** [comment]
I'd just pick the nightly before the feature was stabilized (and add a comment to CI explaining this)

**Comment by sunshowers** [comment]
Thanks, going to land this and get a new version out after it passes CI.

**Comment by smoelius** [comment]
Thanks for being so accommodating!

**Pull request merged**
